Add row Actions to the Table
openshift/dynamic-plugin-sdk pull request #119
Opened 2022-07-01 11:48 UTC by fhlavac

https://issues.redhat.com/browse/HAC-171

Added possibility to define RowActions

![actions](https://user-images.githubusercontent.com/50696716/176888809-077868c5-714a-4ac3-a98e-01abcd2fa021.png)
3

2022-07-21 19:01 UTC, vojtechszocs requested changes
Some minor comments, looks good overall.

2022-07-21 19:01 UTC, vojtechszocs commented on packages/lib-utils/src/components/table/VirtualizedTableBody.tsx
> +          {rowActions ? (
```suggestion
          {rowActions && (
            <Td isActionCell>
              <ActionsColumn items={rowActions} />
            </Td>
          )}
```

2022-07-21 19:08 UTC, vojtechszocs commented
/approved

2022-07-22 14:53 UTC, vidyanambiar reviewed
Thanks @fhlavac!
/lgtm

2022-07-25 17:41 UTC, vojtechszocs commented
/approve

2022-07-25 17:42 UTC, vojtechszocs approved these changes

2022-07-25 17:48 UTC, merged